# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-30 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20160926_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order', 'timestamp']},
        ),
    ]
